[package]
name = "rust-by-example-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.18.2"
num_cpus = "1.0"

[dev-dependencies]
clippy = "0.0.302"
